AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  datadownloadapi:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: .
      Description: ''
      MemorySize: 256
      Timeout: 60
      Layers:
        - 'arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python39:1'
